#!/usr/bin/env python3
"""OpenCDC working-group tool: generate or verify the Table of Contents in a
family markdown document. H1/H2 headings; fenced code blocks excluded.
Usage: python3 tools/generate_toc.py [--check] <doc.md> [<doc2.md> ...]"""
import re, sys

TOC_BEGIN = "<!-- toc:begin (generated by tools/generate_toc.py; do not edit) -->"
TOC_END = "<!-- toc:end -->"

def github_anchor(h):
    a = re.sub(r"[^\w\s-]", "", h.strip().lower())
    return a.replace(" ", "-")

def build_toc(text):
    fenced, toc = False, []
    for ln in text.split("\n"):
        if ln.startswith("```"):
            fenced = not fenced
            continue
        if fenced:
            continue
        m = re.match(r"^(#{1,2}) (.+)$", ln)
        if m and m.group(2).strip() != "Table of Contents":
            toc.append(f"{'  ' * (len(m.group(1)) - 1)}- [{m.group(2).strip()}](#{github_anchor(m.group(2))})")
    return TOC_BEGIN + "\n\n## Table of Contents\n\n" + "\n".join(toc) + "\n\n" + TOC_END

check = "--check" in sys.argv
paths = [a for a in sys.argv[1:] if a != "--check"]
fail = False
for p in paths:
    text = open(p, encoding="utf-8").read()
    m = re.search(re.escape(TOC_BEGIN) + r".*?" + re.escape(TOC_END), text, re.S)
    if not m:
        print(f"{p}: no TOC markers found"); fail = True; continue
    stripped = text[:m.start()] + text[m.end():]
    fresh = build_toc(stripped)
    if m.group(0) == fresh:
        print(f"{p}: TOC up to date" if check else f"{p}: TOC unchanged")
    elif check:
        print(f"{p}: CHECK FAIL -- TOC is stale; regenerate"); fail = True
    else:
        open(p, "w", encoding="utf-8").write(text[:m.start()] + fresh + text[m.end():])
        print(f"{p}: TOC regenerated")
sys.exit(1 if fail else 0)
